#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"

root = File.expand_path("../..", __dir__)
sources = %w[
  hp41cv-functions.json
  hp41-math1-functions.json
  hp41-stat1-functions.json
  hp41-time-functions.json
  hp41-advantage-functions.json
  hp41-xmem-functions.json
].map { |name| File.join(root, "docs", name) }

non_tappable = %w[
  StoReg RclReg StoArith StoArithStack StoM StoN StoO RclM RclN RclO
  StoInd RclInd StoArithInd FmtFix FmtSci FmtEng SfFlag CfFlag SfFlagInd
  CfFlagInd FlagTest FlagTestInd View ViewInd Tone Isg Dse IsgInd DseInd
  Arcl ArclInd Asto AstoInd Gto GtoInd Xeq XeqInd Lbl Clp Del Asn Test
  Add Sub Mul Div Enter Clx Chs Rdn XySwap Lastx PctChange AlphaToggle
  AlphaAppend AlphaBackspace PrgmMode UserMode Catalog GetKey Null
].freeze

entries = sources.flat_map { |path| JSON.parse(File.read(path)) }
  .select { |entry| entry["status"] == "implemented" }
  .reject { |entry| non_tappable.include?(entry["op_variant"]) }
  .uniq { |entry| entry["display_name"] }
  .sort_by { |entry| [entry["category"], entry["display_name"]] }

all_help_entries = sources.flat_map { |path| JSON.parse(File.read(path)) }
  .select { |entry| entry["status"] == "implemented" && entry["op_variant"] != "AlphaClear" }
  .sort_by { |entry| [entry.dig("xrom", "module").to_s, entry["category"], entry["display_name"]] }

shortcuts = JSON.parse(File.read(File.join(root, "docs", "keyboard-shortcuts.json")))

swift_string = ->(value) { JSON.generate(value.to_s) }
rows = entries.map do |entry|
  aliases = Array(entry["search_aliases"]).map { |value| swift_string.call(value) }.join(", ")
  <<~ROW.chomp
          .init(name: #{swift_string.call(entry["display_name"])}, category: #{swift_string.call(entry["category"])}, description: #{swift_string.call(entry["description"])}, aliases: [#{aliases}]),
  ROW
end.join("\n")

help_rows = all_help_entries.map do |entry|
  aliases = Array(entry["search_aliases"]).map { |value| swift_string.call(value) }.join(", ")
  module_name = entry.dig("xrom", "module")
  module_name = entry["category"] == "Extended Memory" ? "Extended Memory" : "HP-41CV Built-in" if module_name.nil?
  example = entry["example"] ? swift_string.call(entry["example"]) : "nil"
  notes = entry["notes"] ? swift_string.call(entry["notes"]) : "nil"
  key_path = entry["key_path"] ? swift_string.call(entry["key_path"]) : "nil"
  runnable = !non_tappable.include?(entry["op_variant"])
  <<~ROW.chomp
          .init(opVariant: #{swift_string.call(entry["op_variant"])}, name: #{swift_string.call(entry["display_name"])}, module: #{swift_string.call(module_name)}, category: #{swift_string.call(entry["category"])}, description: #{swift_string.call(entry["description"])}, keyPath: #{key_path}, example: #{example}, notes: #{notes}, aliases: [#{aliases}], runnable: #{runnable}),
  ROW
end.join("\n")

shortcut_rows = shortcuts.map do |entry|
  "        .init(key: #{swift_string.call(entry["key"])}, operation: #{swift_string.call(entry["op"])}, description: #{swift_string.call(entry["description"])}),"
end.join("\n")

output = <<~SWIFT
  // Generated by scripts/generate-function-catalog.rb. Do not edit by hand.
  import Foundation

  struct FunctionCatalogEntry: Identifiable, Equatable {
      var id: String { name }
      let name: String
      let category: String
      let description: String
      let aliases: [String]

      func matches(_ query: String) -> Bool {
          let needle = query.trimmingCharacters(in: .whitespacesAndNewlines)
          guard !needle.isEmpty else { return true }
          return ([name, category, description] + aliases)
              .contains { $0.localizedCaseInsensitiveContains(needle) }
      }
  }

  enum FunctionCatalog {
      static let all: [FunctionCatalogEntry] = [
  #{rows}    ]
  }

  struct HelpCatalogEntry: Identifiable, Equatable {
      var id: String { opVariant }
      let opVariant: String
      let name: String
      let module: String
      let category: String
      let description: String
      let keyPath: String?
      let example: String?
      let notes: String?
      let aliases: [String]
      let runnable: Bool

      func matches(_ query: String) -> Bool {
          let needle = query.trimmingCharacters(in: .whitespacesAndNewlines)
          guard !needle.isEmpty else { return true }
          return ([name, module, category, description] + aliases)
              .contains { $0.localizedCaseInsensitiveContains(needle) }
      }
  }

  struct ShortcutCatalogEntry: Identifiable, Equatable {
      var id: String { key + operation }
      let key: String
      let operation: String
      let description: String

      func matches(_ query: String) -> Bool {
          let needle = query.trimmingCharacters(in: .whitespacesAndNewlines)
          guard !needle.isEmpty else { return true }
          return [key, operation, description]
              .contains { $0.localizedCaseInsensitiveContains(needle) }
      }
  }

  enum HelpCatalog {
      static let all: [HelpCatalogEntry] = [
  #{help_rows}    ]
      static let shortcuts: [ShortcutCatalogEntry] = [
  #{shortcut_rows}
      ]
      static let modules = Array(Set(all.map(\\.module)).sorted())
  }
SWIFT

destination = File.join(root, "hp41-gui", "Sources", "HP41GUI", "FunctionCatalog.generated.swift")
if ARGV.include?("--check")
  abort "Function catalog is stale; run ruby hp41-gui/scripts/generate-function-catalog.rb" unless File.exist?(destination) && File.read(destination) == output
  puts "Function catalog current (#{entries.length} runnable; #{all_help_entries.length} help entries; #{shortcuts.length} shortcuts)"
else
  File.write(destination, output)
  puts "Generated #{destination} (#{entries.length} runnable; #{all_help_entries.length} help entries; #{shortcuts.length} shortcuts)"
end
